# Generated by Django 5.1.5 on 2025-03-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_image_remove_post_video_postmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
