# Generated by Django 5.1.5 on 2025-03-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_likecomment_reaction_likepost_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likecomment',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('love', 'Love'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('love', 'Love'), ('wow', 'Wow'), ('sad', 'Sad'), ('angry', 'Angry')], default='like', max_length=50, null=True),
        ),
    ]
